/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import { useCallback, useState } from 'react'
import { Col, Nav, Row, Tab, Tabs } from 'react-bootstrap'
import { api } from '../services/api'

import Swal from 'sweetalert2'

import { Container } from '../styles/home'

const Home: NextPage = () => {
  const [key, setKey] = useState<string>('geral');
  const [confirmationCode, setConfirmationCode] = useState<string>('');

  const handleConfirmation = useCallback(async () => {
    console.log('confirmado');
    if (confirmationCode && confirmationCode !== undefined) {
      try {
        const response = await api.post('/confirmation', {
          confirmationCode,
        })
        console.log(response);
        if (response.data.type === 'found') {
          Swal.fire({
            position: 'center',
            icon: 'success',
            title: 'Presença confirmada!',
            text: "Obrigado por fazer parte desse tão momento especial. Sua presença é muito importante para nós!",
          })
        } else if (response.data.type === 'notFound') {
          Swal.fire({
            position: 'center',
            icon: 'question',
            title: 'Oops...',
            text: "Não encontramos seu código de confirmação... Por favor tente novamente ou entre em contato conosco (Marco ou Júlia) para confirmar sua presença.",
          })
        } else if (response.data.type === 'alreadyConfirmed') {
          Swal.fire({
            position: 'center',
            icon: 'info',
            title: 'Presença já confirmada!',
            text: "Sua presença já foi confirmada. Obrigado por fazer parte desse tão momento especial!",
            timer: 5000
          })
        } else {
          Swal.fire({
            position: 'center',
            icon: 'error',
            title: 'Oops...',
            text: "Houve um erro na confirmação! Por favor tente novamente ou entre em contato conosco (Marco ou Júlia) para confirmar sua presença.",
            timer: 5000
          })
        }
      } catch (error) {
        Swal.fire({
          position: 'center',
          icon: 'error',
          title: 'Oops...',
          text: `Houve um erro na confirmação! Por favor tente novamente ou entre em contato conosco (Marco ou Júlia) para confirmar sua presença. - [${error}]`,
          timer: 5000
        })
      }
    }
  }, [confirmationCode])

  return (
    <>
      <Head>
        <title>💘 Casamento Júlia e Marco 💘</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <header className="container-fluid">
          <img
            src="/images/nozes2.jpg"
            alt="Marco a Júlia"
          />
          <div className="tab-menu">
            <div className="menu">
              <a onClick={() => setKey('geral')}>CONFIRMAÇÃO DE PRESENÇA </a>
              <a onClick={() => setKey('outra')}>ENDEREÇO</a>
              <a>PRESENTEIE OS NOIVOS</a>
            </div>
            <div className="tab-bottom" />
          </div>
        </header>

        <div className="container">
          <Tabs
            id="controlled-tab-cliente"
            activeKey={key}
            onSelect={(k) => setKey(`${k}`)}
          >
            <Tab eventKey="geral" title="">
              <section>
                <div className="container">
                  <div className="row">
                    <div className="col-12">
                      <h1>CASAMENTO JÚLIA E MARCO</h1>
                    </div>
                    <div className="col-12">
                      <h3>2 de Julho de 2022</h3>
                    </div>
                    <div className="col-12">
                      <p>Para confirmar sua presença informe abaixo o código recebido em seu convite</p>
                    </div>
                    <div className="col-12">
                      <form>
                        <input
                          type="text"
                          className="form-control"
                          aria-label="Código de confirmação"
                          placeholder='Código de confirmação'
                          onChange={(e) => setConfirmationCode(e.target.value)}
                          value={confirmationCode}
                        />
                        <button type="button" className="btn btn-primary" onClick={handleConfirmation}>
                          CONFIRMAR
                        </button>
                      </form>
                    </div>
                  </div>
                </div>
              </section>
            </Tab>
            <Tab eventKey="outra" title="">
              <section>
                <div className="container">
                  <div className="row">
                    <div className="col-12">
                      <h1>CASAMENTO JÚLIA E MARCO</h1>
                    </div>
                    <div className="col-12">
                      <h3>2 de Julho de 2022</h3>
                    </div>
                    <div className="col-12">
                      <p>Gramado, Redenção da Serra - SP (Via Rodovía Otácilio F. da Silva)</p>
                    </div>
                    <div className="col-12 d-flex justify-content-center">
                      <small>Clique no mapa para ver a localização completa</small>
                    </div>
                    <div className="col-12 map">
                      <a target="_blank" href="https://www.google.com.br/maps/place/Chácara+Família+Lima/@-23.2959127,-45.5030806,17z/data=!4m12!1m6!3m5!1s0x94cd0f7a5d47489b:0xf68b2b6cdcb644d7!2sChácara+Família+Lima!8m2!3d-23.2959127!4d-45.5008919!3m4!1s0x94cd0f7a5d47489b:0xf68b2b6cdcb644d7!8m2!3d-23.2959127!4d-45.5008919" rel="noreferrer">
                        <img src="/images/redencao.jpg" className="img-responsive" />
                      </a>
                    </div>
                  </div>
                </div>
              </section>
            </Tab>
          </Tabs>
        </div>

      </Container>
    </>
  )
}

export default Home
